# 公共配置文件
spring:
  application:
    name: friendship-line-backend
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yupi?serverTimezone=Asia/Shanghai
    username: root
    password: root
  # session 失效时间 (分钟) 2个月
  session:
    timeout: 86400
    # 使用Redis作为会话存储
    store-type: redis
  redis:
    port: 6379
    host: localhost
    database: 3
server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        #cookie将仅在localhost域上有效，
        #从而限制了cookie的共享范围，增加了安全性
        domain: localhost
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
# 接口文档配置
#springdoc:
#  group-configs:
#    - group: 'default'
#      packages-to-scan: com.taoshao.friendshipline.controller
## knife4j的增强配置，不需要增强可以不配
#knife4j:
#  enable: true
#  setting:
#    language: zh_cn
knife4j:
  enable: true
  openapi:
    title: 友链
    description: "接口测试"
    concat: 涛少
    version: v4.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.taoshao.friendshipline.controller